### PR TITLE
added option --raw-input which sets that the input file can be XML file (e.g. fodt)

### PR DESCRIPTION
**Pull request by shenek**
My goal is to make odt2txt to support fodt file format.

I have tested this patch with a several fodt files and It seems to be working.

### CODE REVIEW

**Comment by davidfraser** [comment]
I've tested this and it works correctly on my examples; without this patch `.fodt` files are simply rejected. Since having `fodt` files in version control overlaps in purpose with a common use of `odt2txt` (to diff OpenDocument files in version control more naturally), this is a helpful improvement.

**Comment by Vdragon** [comment]
:+1: for this too as I really need clean git diff of my flat-XML documents

**Comment by KlfJoat** [comment]
I'm going to nudge this, because this would be wonderful for my use case.

**Comment by MayeulC** [comment]
would it be possible to add a mention of `--raw-input` in the `Can't read from xxx.fodt: Is it an OpenDocument Text?` error message? I opened #14 because I missed the switch.

**Comment by alfinal** [comment]
Also I want to suggest something:

**introduction:**
`odt2txt` is deeply used to get a `txt` file to could use `git diff` for LibreOffice files stored in Git

If you store files in `.odt` and you add in your git config:
`git config diff.odf.textconv odt2txt` you can use `git diff` for those files (but control versioning make file size huge because git can not deal with zipped binaries.

If you try to store files in `.fodt` you deal with a regular file size after a lot of versioning, but you can not use `git diff` because `git config` doesn't accept parameters.

**so my suggestion is:**
directly, `odt2txt` just accept `.fodt` just detect that is just a raw flat document.

Of course there are some workaround to avoid that, also somebody developed his/her own simple [fodt2txt in C#](https://github.com/codingatty/fodt2txt) but I think that is a good improvement just this program do the work. IMHO when a user uses `odt2txt` doesn't care if is trying to convert a `.odt`, `.ods`, `.fodt`,...

**Pull request merged**
